export const categories = [
  'Spices',
  'Dairy',
  'Meat',
  'Flour & Grains',
  'Fruits',
  'Vegetables',
  'Herbs',
  'Oils & Vinegars',
  'Sweeteners',
  'Nuts & Seeds',
  'Condiments & Sauces',
  'Canned/Preserved',
  'Baking Essentials',
  'Seafood',
  'Legumes',
];

export const allItems = {
  Spices: [
    'Biryani Masala',
    'Red Chili',
    'Coriander',
    'Turmeric',
    'Garam Masala',
    'Cumin',
    'Cardamom',
    'Saffron',
  ],
  Dairy: ['Yogurt', 'Milk', 'Ghee', 'Cream'],
  Meat: ['Chicken', 'Beef', 'Mutton'],
  'Flour & Grains': ['Basmati Rice', 'Wheat', 'Barley', 'Flour'],
  Fruits: ['Lemon', 'Raisins'],
  Vegetables: [
    'Onions',
    'Tomatoes',
    'Spinach',
    'Mustard',
    'Carrots',
    'Potatoes',
    'Bell Peppers',
  ],
  Herbs: ['Fresh Coriander', 'Cilantro'],
  'Oils & Vinegars': ['Cooking Oil', 'Ghee'],
  Sweeteners: ['Sugar'],
  'Nuts & Seeds': ['Almonds'],
  'Condiments & Sauces': ['Mustard'],
  'Canned/Preserved': [],
  'Baking Essentials': [],
  Seafood: [],
  Legumes: ['Lentils', 'Chickpeas'],
};
