export const categories = [
  'Spices',
  'Dairy',
  'Meat',
  'Flour & Grains',
  'Fruits',
  'Vegetables',
  'Herbs',
  'Oils & Vinegars',
  'Sweeteners',
  'Nuts & Seeds',
  'Condiments & Sauces',
  'Canned/Preserved',
  'Baking Essentials',
  'Seafood',
  'Legumes',
];

export const allItems = {
  Spices: [
    'Turmeric',
    'Cumin',
    'Paprika',
    'Cinnamon',
    'Chili Powder',
    'Black Pepper',
    'Saffron',
    'Sumac',
    'Cardamom',
    'Nutmeg',
    'Biryani Masala',
    'Nihari Masala',
    'Shawarma Spice Mix',
    'Taco Seasoning',
    'Gochugaru', // Korean chili powder
    'Five-Spice Powder',
    'Chaat Masala',
  ],
  Dairy: [
    'Eggs',
    'Milk',
    'Butter',
    'Heavy Cream',
    'Yogurt',
    'Cheese (Cheddar)',
    'Sour Cream',
    'Ricotta Cheese',
    'Mozzarella Cheese',
    'Parmesan Cheese',
    'Feta Cheese',
    'Labneh',
    'Jameed',
    'Mascarpone Cheese',
    'Cream Cheese',
  ],
  Meat: [
    'Chicken Breast',
    'Ground Beef',
    'Bacon',
    'Sausage',
    'Chicken Thighs',
    'Beef Shank',
    'Lamb',
    'Ground Chicken',
    'Duck (Halal)',
  ],
  'Flour & Grains': [
    'All-Purpose Flour',
    'Bread Flour',
    'Whole Wheat Flour',
    'Rice Flour',
    'Rice',
    'Quinoa',
    'Oats',
    'Cornmeal',
    'Bulgur Wheat',
    'Phyllo Dough',
    'Kataifi Dough',
    'Sweet Potato Noodles',
    'Rice Cakes',
    'Glutinous Rice',
    'Spring Roll Wrappers',
    'Dumpling Wrappers',
    'Puff Pastry',
    'Vermicelli',
  ],
  Fruits: [
    'Apples',
    'Bananas',
    'Lemons',
    'Limes',
    'Raisins',
    'Dried Cranberries',
    'Pomegranate Seeds',
    'Dates',
    'Coconut Flakes',
  ],
  Vegetables: [
    'Onions',
    'Garlic',
    'Carrots',
    'Tomatoes',
    'Spinach',
    'Bell Peppers',
    'Potatoes',
    'Eggplant',
    'Cauliflower',
    'Zucchini',
    'Bamboo Shoots',
    'Bok Choy',
    'Mushrooms',
    'Radishes',
    'Bean Sprouts',
    'Mustard Greens',
  ],
  Herbs: ['Basil', 'Parsley', 'Thyme', 'Rosemary', 'Cilantro', 'Mint', 'Dill'],
  'Oils & Vinegars': [
    'Olive Oil',
    'Vegetable Oil',
    'Sesame Oil',
    'Balsamic Vinegar',
    'Apple Cider Vinegar',
    'Ghee',
    'Rice Vinegar',
    'White Vinegar',
  ],
  Sweeteners: [
    'Sugar',
    'Honey',
    'Maple Syrup',
    'Brown Sugar',
    'Agave Nectar',
    'Powdered Sugar',
  ],
  'Nuts & Seeds': [
    'Almonds',
    'Walnuts',
    'Chia Seeds',
    'Flaxseeds',
    'Peanuts',
    'Pumpkin Seeds',
    'Pistachios',
    'Cashews',
    'Pine Nuts',
    'Sesame Seeds',
  ],
  'Condiments & Sauces': [
    'Soy Sauce',
    'Tomato Paste',
    'Mustard',
    'Mayonnaise',
    'Hot Sauce',
    'Worcestershire Sauce',
    'Hoisin Sauce',
    'Oyster Sauce',
    'Fish Sauce',
    'Gochujang', // Korean chili paste
    'Tahini',
    'Chili Bean Paste',
    'Garlic Sauce',
    'Sweet Chili Sauce',
  ],
  'Canned/Preserved': [
    'Canned Tomatoes',
    'Black Beans',
    'Coconut Milk',
    'Pickles',
    'Olives',
    'Kimchi',
    'Preserved Lemon',
    'Pickled Vegetables',
  ],
  'Baking Essentials': [
    'Baking Soda',
    'Baking Powder',
    'Vanilla Extract',
    'Yeast',
    'Chocolate Chips',
    'Gelatin',
  ],
  Seafood: ['Salmon Fillet', 'Shrimp', 'Tuna Steak', 'Mussels', 'Cod', 'Clams'],
  Legumes: [
    'Lentils',
    'Chickpeas',
    'Kidney Beans',
    'Split Peas',
    'Black-Eyed Peas',
    'Cannellini Beans',
  ],
};
