export const recipes = [
  {
    name: 'Chicken Biryani',
    cuisine: 'Pakistani',
    image: '../assets/images/CB.png',
    ingredients: [
      'basmati rice',
      'chicken',
      'yogurt',
      'ginger-garlic paste',
      'biryani masala',
      'onions',
      'oil',
      'saffron',
    ],
    recipeSteps: [
      'Marinate chicken in yogurt, spices, and ginger-garlic paste for 1 hour.',
      'Sauté onions until golden. Layer partially cooked rice and chicken in a pot.',
      'Add saffron and cook on low heat for 30 minutes (dum cooking).',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Nihari',
    cuisine: 'Pakistani',
    ingredients: [
      'beef shank',
      'wheat flour',
      'ginger',
      'garlic',
      'nihari masala',
      'oil',
      'ginger juliennes',
      'lemon',
    ],
    recipeSteps: [
      'Slow-cook beef with spices and water for 4-5 hours until tender.',
      'Mix wheat flour with water to make a paste. Stir into stew to thicken.',
      'Garnish with ginger and lemon. Serve with naan.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Daal Chawal',
    cuisine: 'Pakistani',
    ingredients: [
      'lentils',
      'rice',
      'onions',
      'tomatoes',
      'turmeric',
      'cumin',
      'garlic',
      'green chilies',
    ],
    recipeSteps: [
      'Boil lentils with turmeric until soft. Cook rice separately.',
      'Sauté onions, garlic, tomatoes, and cumin in oil.',
      'Mix lentils with the sautéed mixture. Serve over rice with green chilies.',
    ],
    allergies: [],
  },
  {
    name: 'Seekh Kebabs',
    cuisine: 'Pakistani',
    ingredients: [
      'ground beef',
      'onions',
      'garlic',
      'coriander',
      'cumin',
      'paprika',
      'egg',
      'breadcrumbs',
    ],
    recipeSteps: [
      'Mix beef, spices, egg, and breadcrumbs. Shape onto skewers.',
      'Grill on high heat for 8-10 minutes, turning occasionally.',
    ],
    allergies: ['eggs', 'gluten'],
  },
  {
    name: 'Haleem',
    cuisine: 'Pakistani',
    ingredients: [
      'wheat',
      'lentils',
      'chicken',
      'ginger',
      'garlic',
      'spices',
      'ghee',
      'fried onions',
    ],
    recipeSteps: [
      'Slow-cook wheat, lentils, and chicken with spices for 6-8 hours.',
      'Blend into a thick porridge. Stir in ghee.',
      'Garnish with fried onions and serve with lemon.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Chicken Karahi',
    cuisine: 'Pakistani',
    ingredients: [
      'chicken',
      'tomatoes',
      'ginger',
      'garlic',
      'green chilies',
      'coriander',
      'karahi masala',
      'oil',
    ],
    recipeSteps: [
      'Sauté ginger, garlic, and chicken in oil until browned.',
      'Add tomatoes and spices. Cook until oil separates.',
      'Garnish with coriander and green chilies.',
    ],
    allergies: [],
  },
  {
    name: 'Aloo Gosht',
    cuisine: 'Pakistani',
    ingredients: [
      'beef',
      'potatoes',
      'onions',
      'tomatoes',
      'garlic',
      'ginger',
      'turmeric',
      'coriander powder',
    ],
    recipeSteps: [
      'Sauté onions, ginger, and garlic. Add beef and brown.',
      'Add tomatoes, spices, and water. Simmer until beef is tender.',
      'Add potatoes and cook until soft.',
    ],
    allergies: [],
  },
  {
    name: 'Chapli Kebabs',
    cuisine: 'Pakistani',
    ingredients: [
      'ground beef',
      'tomatoes',
      'green chilies',
      'coriander',
      'pomegranate seeds',
      'corn flour',
      'egg',
    ],
    recipeSteps: [
      'Mix beef, chopped tomatoes, chilies, spices, and egg.',
      'Shape into patties. Pan-fry until crispy.',
    ],
    allergies: ['eggs'],
  },
  {
    name: 'Beef Pulao',
    cuisine: 'Pakistani',
    ingredients: [
      'basmati rice',
      'beef',
      'onions',
      'garlic',
      'cinnamon',
      'cloves',
      'oil',
      'water',
    ],
    recipeSteps: [
      'Sauté onions, garlic, and beef until browned.',
      'Add rice, spices, and water. Cook until rice is fluffy.',
    ],
    allergies: [],
  },
  {
    name: 'Chicken Tikka',
    cuisine: 'Pakistani',
    ingredients: [
      'chicken thighs',
      'yogurt',
      'ginger-garlic paste',
      'lemon juice',
      'tikka masala',
      'oil',
    ],
    recipeSteps: [
      'Marinate chicken in yogurt, spices, and lemon juice for 2 hours.',
      'Grill or bake until charred and cooked through.',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Chana Masala',
    cuisine: 'Pakistani',
    ingredients: [
      'chickpeas',
      'onions',
      'tomatoes',
      'ginger-garlic paste',
      'turmeric',
      'garam masala',
      'coriander',
    ],
    recipeSteps: [
      'Boil chickpeas until soft. Sauté onions, ginger-garlic paste, and spices in oil.',
      'Add tomatoes and chickpeas. Simmer for 15 minutes. Garnish with coriander.',
    ],
    allergies: [],
  },
  {
    name: 'Aloo Paratha',
    cuisine: 'Pakistani',
    ingredients: ['wheat flour', 'potatoes', 'cumin', 'green chilies', 'oil'],
    recipeSteps: [
      'Make dough with flour and water. Stuff with spiced mashed potatoes.',
      'Roll into flatbreads and cook on a griddle with oil.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Saag',
    cuisine: 'Pakistani',
    ingredients: [
      'spinach',
      'mustard greens',
      'onions',
      'ginger',
      'garlic',
      'cornmeal',
    ],
    recipeSteps: [
      'Cook spinach and greens until soft. Blend into a paste.',
      'Sauté onions, ginger, and garlic. Add greens and simmer with cornmeal.',
    ],
    allergies: [],
  },
  {
    name: 'Kheer',
    cuisine: 'Pakistani',
    ingredients: ['rice', 'milk', 'sugar', 'cardamom', 'almonds', 'raisins'],
    recipeSteps: [
      'Simmer rice in milk until thick. Add sugar and cardamom.',
      'Garnish with nuts and raisins. Serve chilled.',
    ],
    allergies: ['dairy', 'nuts'],
  },
  {
    name: 'Chicken Handi',
    cuisine: 'Pakistani',
    ingredients: [
      'chicken',
      'yogurt',
      'cream',
      'tomatoes',
      'ginger-garlic paste',
      'green chilies',
    ],
    recipeSteps: [
      'Cook chicken with ginger-garlic paste and spices.',
      'Add yogurt, cream, and tomatoes. Simmer until creamy.',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Beef Kofta',
    cuisine: 'Pakistani',
    ingredients: [
      'ground beef',
      'onions',
      'coriander',
      'mint',
      'egg',
      'tomato gravy',
    ],
    recipeSteps: [
      'Mix beef, onions, herbs, and egg. Shape into meatballs.',
      'Cook in tomato-based gravy for 20 minutes.',
    ],
    allergies: ['eggs'],
  },
  {
    name: 'Gajar ka Halwa',
    cuisine: 'Pakistani',
    ingredients: ['carrots', 'milk', 'sugar', 'ghee', 'cardamom', 'cashews'],
    recipeSteps: [
      'Grate carrots and cook in milk until thick.',
      'Add sugar, ghee, and cardamom. Garnish with fried cashews.',
    ],
    allergies: ['dairy', 'nuts'],
  },
  {
    name: 'Tandoori Roti',
    cuisine: 'Pakistani',
    ingredients: ['wheat flour', 'yeast', 'water', 'salt'],
    recipeSteps: [
      'Knead dough with flour, yeast, and water. Let it rise for 1 hour.',
      'Roll into circles and bake in a tandoor or oven.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Chicken Jalfrezi',
    cuisine: 'Pakistani',
    ingredients: [
      'chicken',
      'bell peppers',
      'onions',
      'tomatoes',
      'ginger-garlic paste',
      'cumin',
    ],
    recipeSteps: [
      'Stir-fry chicken with onions and ginger-garlic paste.',
      'Add peppers, tomatoes, and spices. Cook until tender.',
    ],
    allergies: [],
  },
  {
    name: 'Pakora',
    cuisine: 'Pakistani',
    ingredients: [
      'chickpea flour',
      'onions',
      'potatoes',
      'spinach',
      'green chilies',
      'oil',
    ],
    recipeSteps: [
      'Mix veggies with chickpea flour and water to make a batter.',
      'Deep-fry spoonfuls until golden and crispy.',
    ],
    allergies: [],
  },

  {
    name: 'Margherita Pizza',
    cuisine: 'Italian',
    ingredients: [
      'pizza dough',
      'tomato sauce',
      'mozzarella cheese',
      'fresh basil',
      'olive oil',
    ],
    recipeSteps: [
      'Preheat oven to 475°F (245°C).',
      'Spread tomato sauce on dough, top with cheese.',
      'Bake for 10-12 minutes. Garnish with basil and olive oil.',
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Spaghetti Aglio e Olio',
    cuisine: 'Italian',
    ingredients: [
      'spaghetti',
      'garlic cloves',
      'red chili flakes',
      'parsley',
      'olive oil',
    ],
    recipeSteps: [
      'Cook spaghetti until al dente.',
      'Sauté garlic and chili flakes in olive oil.',
      'Toss pasta in garlic oil. Garnish with parsley.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Risotto alla Milanese',
    cuisine: 'Italian',
    ingredients: [
      'arborio rice',
      'saffron',
      'onion',
      'butter',
      'parmesan',
      'vegetable broth',
    ],
    recipeSteps: [
      'Sauté onion in butter. Add rice and toast for 2 minutes.',
      'Gradually add broth, stirring until absorbed.',
      'Stir in saffron and parmesan. Serve creamy.',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Lasagna',
    cuisine: 'Italian',
    ingredients: [
      'lasagna sheets',
      'ground beef',
      'ricotta cheese',
      'tomato sauce',
      'mozzarella',
    ],
    recipeSteps: [
      'Layer cooked lasagna sheets, beef, tomato sauce, ricotta, and mozzarella.',
      'Repeat layers. Bake at 375°F (190°C) for 45 minutes.',
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Focaccia',
    cuisine: 'Italian',
    ingredients: ['flour', 'yeast', 'olive oil', 'rosemary', 'sea salt'],
    recipeSteps: [
      'Knead dough with flour, yeast, water, and olive oil. Let rise 1 hour.',
      'Press dough into a pan. Dimple with fingers, top with rosemary and salt.',
      'Bake at 425°F (220°C) for 20 minutes.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Minestrone Soup',
    cuisine: 'Italian',
    ingredients: [
      'carrots',
      'zucchini',
      'cannellini beans',
      'pasta',
      'tomatoes',
      'vegetable broth',
    ],
    recipeSteps: [
      'Sauté chopped veggies in olive oil.',
      'Add broth, tomatoes, and beans. Simmer 20 minutes.',
      'Add pasta and cook until tender.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Caprese Salad',
    cuisine: 'Italian',
    ingredients: [
      'mozzarella cheese',
      'tomatoes',
      'basil',
      'olive oil',
      'balsamic vinegar',
    ],
    recipeSteps: [
      'Slice tomatoes and mozzarella. Layer alternately.',
      'Drizzle with olive oil and balsamic. Top with basil.',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Tiramisu',
    cuisine: 'Italian',
    ingredients: [
      'ladyfingers',
      'mascarpone cheese',
      'espresso',
      'cocoa powder',
      'eggs',
      'sugar',
    ],
    recipeSteps: [
      'Beat egg yolks with sugar. Mix with mascarpone.',
      'Dip ladyfingers in espresso. Layer with mascarpone cream.',
      'Refrigerate 4 hours. Dust with cocoa.',
    ],
    allergies: ['dairy', 'eggs', 'gluten'],
  },
  {
    name: 'Bruschetta',
    cuisine: 'Italian',
    ingredients: ['baguette', 'tomatoes', 'garlic', 'basil', 'olive oil'],
    recipeSteps: [
      'Toast sliced baguette until crisp.',
      'Rub with garlic. Top with diced tomatoes, basil, and oil.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Pasta Carbonara',
    cuisine: 'Italian',
    ingredients: [
      'spaghetti',
      'eggs',
      'pecorino cheese',
      'black pepper',
      'pancetta',
    ],
    recipeSteps: [
      'Cook pasta. Sauté pancetta until crispy.',
      'Mix eggs, cheese, and pepper. Toss with hot pasta and pancetta.',
    ],
    allergies: ['gluten', 'dairy', 'eggs'],
  },
  {
    name: 'Gnocchi',
    cuisine: 'Italian',
    ingredients: ['potatoes', 'flour', 'egg', 'salt'],
    recipeSteps: [
      'Boil and mash potatoes. Mix with flour and egg.',
      'Roll dough into ropes, cut into pieces.',
      'Boil until gnocchi float. Serve with sauce.',
    ],
    allergies: ['gluten', 'eggs'],
  },
  {
    name: 'Ravioli',
    cuisine: 'Italian',
    ingredients: [
      'pasta dough',
      'ricotta cheese',
      'spinach',
      'parmesan',
      'nutmeg',
    ],
    recipeSteps: [
      'Mix ricotta, spinach, parmesan, and nutmeg for filling.',
      'Place filling between pasta sheets. Cut into squares.',
      'Boil ravioli for 3-4 minutes. Serve with tomato sauce.',
    ],
    allergies: ['gluten', 'dairy'],
  },
  {
    name: 'Chicken Parmigiana',
    cuisine: 'Italian',
    ingredients: [
      'chicken breasts',
      'breadcrumbs',
      'marinara sauce',
      'mozzarella',
      'parmesan',
    ],
    recipeSteps: [
      'Coat chicken in breadcrumbs. Pan-fry until golden.',
      'Top with marinara and cheese. Bake at 375°F (190°C) for 15 minutes.',
    ],
    allergies: ['gluten', 'dairy'],
  },
  {
    name: 'Osso Buco',
    cuisine: 'Italian',
    ingredients: [
      'veal shanks',
      'carrots',
      'onion',
      'celery',
      'white wine',
      'broth',
    ],
    recipeSteps: [
      'Brown veal shanks in oil. Remove and sauté veggies.',
      'Deglaze with wine. Add broth and veal. Simmer 2 hours.',
    ],
    allergies: [],
  },
  {
    name: 'Panzanella',
    cuisine: 'Italian',
    ingredients: [
      'stale bread',
      'tomatoes',
      'cucumber',
      'red onion',
      'olive oil',
      'vinegar',
    ],
    recipeSteps: [
      'Tear bread into chunks. Soak in water, then squeeze dry.',
      'Toss with chopped veggies, oil, and vinegar.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Cannoli',
    cuisine: 'Italian',
    ingredients: [
      'cannoli shells',
      'ricotta cheese',
      'powdered sugar',
      'chocolate chips',
    ],
    recipeSteps: [
      'Mix ricotta, sugar, and chocolate chips.',
      'Pipe filling into cannoli shells. Dust with powdered sugar.',
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Polenta',
    cuisine: 'Italian',
    ingredients: ['cornmeal', 'water', 'butter', 'parmesan', 'salt'],
    recipeSteps: [
      'Boil water. Whisk in cornmeal and cook until thick.',
      'Stir in butter and parmesan. Serve creamy or chilled and sliced.',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Panna Cotta',
    cuisine: 'Italian',
    ingredients: [
      'heavy cream',
      'sugar',
      'vanilla extract',
      'gelatin',
      'berries',
    ],
    recipeSteps: [
      'Heat cream, sugar, and vanilla. Dissolve gelatin in the mix.',
      'Pour into molds. Chill 4 hours. Serve with berries.',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Calzone',
    cuisine: 'Italian',
    ingredients: ['pizza dough', 'ricotta', 'mozzarella', 'ham', 'marinara'],
    recipeSteps: [
      'Roll dough into circles. Fill with cheese and ham.',
      'Fold and seal edges. Bake at 400°F (200°C) for 20 minutes.',
    ],
    allergies: ['gluten', 'dairy'],
  },
  {
    name: 'Ribollita',
    cuisine: 'Italian',
    ingredients: [
      'bread',
      'cannellini beans',
      'kale',
      'tomatoes',
      'carrots',
      'onion',
    ],
    recipeSteps: [
      'Sauté veggies. Add beans, tomatoes, and broth. Simmer 30 minutes.',
      'Tear bread into soup. Reheat before serving.',
    ],
    allergies: ['gluten'],
  },

  {
    name: 'Beef Tacos',
    cuisine: 'Mexican',
    ingredients: [
      'ground beef',
      'taco seasoning',
      'corn tortillas',
      'lettuce',
      'tomatoes',
      'lime',
      'guacamole',
    ],
    recipeSteps: [
      'Cook beef with taco seasoning until browned.',
      'Warm tortillas. Assemble with beef, lettuce, tomatoes, and guacamole.',
      'Serve with lime wedges.',
    ],
    allergies: [],
  },
  {
    name: 'Chicken Quesadillas',
    cuisine: 'Mexican',
    ingredients: [
      'flour tortillas',
      'cooked chicken',
      'cheddar cheese',
      'bell peppers',
      'salsa',
    ],
    recipeSteps: [
      'Layer chicken, cheese, and peppers on half a tortilla.',
      'Fold and cook in a skillet until crispy. Serve with salsa.',
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Guacamole',
    cuisine: 'Mexican',
    ingredients: [
      'avocados',
      'lime juice',
      'tomatoes',
      'onion',
      'cilantro',
      'jalapeño',
    ],
    recipeSteps: [
      'Mash avocados. Mix with lime juice, tomatoes, onion, cilantro, and jalapeño.',
      'Season with salt.',
    ],
    allergies: [],
  },
  {
    name: 'Enchiladas Verdes',
    cuisine: 'Mexican',
    ingredients: [
      'corn tortillas',
      'chicken',
      'green salsa',
      'cream',
      'cheese',
    ],
    recipeSteps: [
      'Fill tortillas with shredded chicken. Roll and place in a baking dish.',
      'Cover with salsa and cheese. Bake at 350°F (175°C) for 20 minutes.',
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Churros',
    cuisine: 'Mexican',
    ingredients: ['water', 'flour', 'sugar', 'cinnamon', 'oil'],
    recipeSteps: [
      'Boil water, flour, and sugar to make dough. Pipe into hot oil.',
      'Fry until golden. Roll in cinnamon-sugar.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Hummus',
    cuisine: 'Arab',
    ingredients: ['chickpeas', 'tahini', 'lemon juice', 'garlic', 'olive oil'],
    recipeSteps: [
      'Blend chickpeas, tahini, lemon juice, and garlic until smooth.',
      'Drizzle with olive oil before serving.',
    ],
    allergies: ['sesame (tahini)'],
  },
  {
    name: 'Shawarma',
    cuisine: 'Arab',
    ingredients: [
      'chicken thighs',
      'shawarma spice mix',
      'garlic',
      'lemon juice',
      'pita bread',
      'garlic sauce',
    ],
    recipeSteps: [
      'Marinate chicken in spices and lemon juice for 2 hours.',
      'Grill until charred. Slice and serve in pita with garlic sauce.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Falafel',
    cuisine: 'Arab',
    ingredients: [
      'chickpeas',
      'parsley',
      'cumin',
      'garlic',
      'baking soda',
      'oil',
    ],
    recipeSteps: [
      'Blend soaked chickpeas, herbs, and spices.',
      'Form into balls. Deep-fry until crispy.',
    ],
    allergies: [],
  },
  {
    name: 'Tabbouleh',
    cuisine: 'Arab',
    ingredients: [
      'bulgur wheat',
      'parsley',
      'tomatoes',
      'mint',
      'lemon juice',
      'olive oil',
    ],
    recipeSteps: [
      'Soak bulgur in water. Mix with chopped herbs and tomatoes.',
      'Toss with lemon juice and olive oil.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Baklava',
    cuisine: 'Arab',
    ingredients: [
      'phyllo dough',
      'pistachios',
      'walnuts',
      'sugar',
      'butter',
      'honey',
    ],
    recipeSteps: [
      'Layer phyllo sheets with butter and nuts.',
      'Bake at 350°F (175°C) for 30 minutes. Pour honey syrup over.',
    ],
    allergies: ['nuts', 'gluten'],
  },
  {
    name: 'Fattoush Salad',
    cuisine: 'Arab',
    ingredients: [
      'romaine lettuce',
      'cucumbers',
      'radishes',
      'pita chips',
      'sumac',
      'lemon dressing',
    ],
    recipeSteps: [
      'Toss chopped veggies with pita chips.',
      'Dress with lemon, olive oil, and sumac.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Mansaf',
    cuisine: 'Arab',
    ingredients: ['lamb', 'jameed', 'rice', 'almonds', 'pita bread'],
    recipeSteps: [
      'Cook lamb in jameed sauce until tender.',
      'Serve over rice with toasted almonds and pita.',
    ],
    allergies: ['dairy', 'nuts'],
  },
  {
    name: 'Kabsa',
    cuisine: 'Arab',
    ingredients: [
      'basmati rice',
      'chicken',
      'kabsa spices',
      'tomatoes',
      'onions',
    ],
    recipeSteps: [
      'Brown chicken. Cook rice in spiced chicken broth.',
      'Serve chicken over rice with sautéed veggies.',
    ],
    allergies: [],
  },
  {
    name: 'Maqluba',
    cuisine: 'Arab',
    ingredients: ['rice', 'eggplant', 'cauliflower', 'chicken', 'turmeric'],
    recipeSteps: [
      'Layer veggies and chicken in a pot. Add rice and spices.',
      'Cook until done. Invert onto a plate before serving.',
    ],
    allergies: [],
  },
  {
    name: 'Kunafa',
    cuisine: 'Arab',
    ingredients: [
      'kataifi dough',
      'ricotta cheese',
      'sugar syrup',
      'pistachios',
    ],
    recipeSteps: [
      'Layer dough and cheese in a pan. Bake until golden.',
      'Pour sugar syrup over. Garnish with pistachios.',
    ],
    allergies: ['dairy', 'nuts', 'gluten'],
  },
  {
    name: 'Labneh',
    cuisine: 'Arab',
    ingredients: ['Greek yogurt', 'olive oil', "za'atar", 'pita bread'],
    recipeSteps: [
      'Strain yogurt overnight to thicken.',
      "Serve with olive oil, za'atar, and pita.",
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Mutabbal',
    cuisine: 'Arab',
    ingredients: ['eggplant', 'tahini', 'lemon juice', 'garlic', 'yogurt'],
    recipeSteps: [
      'Roast eggplant until soft. Peel and blend with tahini, garlic, and yogurt.',
      'Drizzle with olive oil.',
    ],
    allergies: ['tahini', 'dairy'],
  },
  {
    name: 'Dolma',
    cuisine: 'Arab',
    ingredients: ['grape leaves', 'rice', 'ground beef', 'dill', 'lemon'],
    recipeSteps: [
      'Mix rice, beef, and herbs. Wrap in grape leaves.',
      'Steam with lemon juice for 45 minutes.',
    ],
    allergies: [],
  },
  {
    name: 'Umm Ali',
    cuisine: 'Arab',
    ingredients: ['puff pastry', 'milk', 'sugar', 'raisins', 'coconut flakes'],
    recipeSteps: [
      'Layer pastry pieces in a dish. Pour sweetened milk over.',
      'Bake at 375°F (190°C) for 20 minutes. Top with coconut.',
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Chicken Mandi',
    cuisine: 'Arab',
    ingredients: [
      'chicken',
      'basmati rice',
      'mandi spices',
      'onions',
      'almonds',
    ],
    recipeSteps: [
      'Marinate chicken in spices. Roast over charcoal.',
      'Cook rice in spiced broth. Serve with chicken and almonds.',
    ],
    allergies: ['nuts'],
  },

  {
    name: 'Fried Rice',
    cuisine: 'Chinese',
    ingredients: [
      'cooked rice',
      'eggs',
      'carrots',
      'peas',
      'soy sauce',
      'sesame oil',
    ],
    recipeSteps: [
      'Scramble eggs in oil. Add chopped veggies and stir-fry.',
      'Add rice and soy sauce. Toss for 5 minutes.',
    ],
    allergies: ['eggs', 'soy'],
  },
  {
    name: 'Kung Pao Chicken',
    cuisine: 'Chinese',
    ingredients: [
      'chicken',
      'peanuts',
      'soy sauce',
      'vinegar',
      'chili peppers',
      'garlic',
    ],
    recipeSteps: [
      'Stir-fry chicken with garlic and chilies.',
      'Add peanuts and sauce. Simmer until thickened.',
    ],
    allergies: ['nuts', 'soy'],
  },
  {
    name: 'Chow Mein',
    cuisine: 'Chinese',
    ingredients: [
      'wheat noodles',
      'chicken',
      'bell peppers',
      'soy sauce',
      'bean sprouts',
    ],
    recipeSteps: [
      'Boil noodles. Stir-fry chicken and veggies.',
      'Add noodles and soy sauce. Toss to combine.',
    ],
    allergies: ['gluten', 'soy'],
  },
  {
    name: 'Spring Rolls',
    cuisine: 'Chinese',
    ingredients: [
      'spring roll wrappers',
      'cabbage',
      'carrots',
      'shrimp',
      'soy sauce',
    ],
    recipeSteps: [
      'Sauté veggies and shrimp. Fill wrappers and roll.',
      'Deep-fry until golden.',
    ],
    allergies: ['gluten', 'shellfish', 'soy'],
  },
  {
    name: 'Dumplings (Jiaozi)',
    cuisine: 'Chinese',
    ingredients: [
      'dumpling wrappers',
      'ground pork (Halal chicken substitute)',
      'cabbage',
      'ginger',
      'soy sauce',
    ],
    recipeSteps: [
      'Mix filling ingredients. Fill wrappers and seal.',
      'Boil or pan-fry until cooked.',
    ],
    allergies: ['gluten', 'soy'],
  },
  {
    name: 'Hot and Sour Soup',
    cuisine: 'Chinese',
    ingredients: [
      'tofu',
      'mushrooms',
      'bamboo shoots',
      'vinegar',
      'soy sauce',
      'eggs',
    ],
    recipeSteps: [
      'Boil broth with veggies and tofu.',
      'Add soy sauce, vinegar, and beaten eggs. Stir gently.',
    ],
    allergies: ['eggs', 'soy'],
  },
  {
    name: 'Mapo Tofu',
    cuisine: 'Chinese',
    ingredients: [
      'tofu',
      'ground beef (Halal)',
      'chili bean paste',
      'garlic',
      'soy sauce',
    ],
    recipeSteps: [
      'Sauté beef with garlic and chili paste.',
      'Add tofu and simmer in sauce.',
    ],
    allergies: ['soy'],
  },
  {
    name: 'Wonton Soup',
    cuisine: 'Chinese',
    ingredients: [
      'wonton wrappers',
      'ground chicken',
      'ginger',
      'chicken broth',
      'green onions',
    ],
    recipeSteps: [
      'Fill wrappers with chicken and ginger. Seal into wontons.',
      'Boil in broth until cooked. Garnish with onions.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Sweet and Sour Pork (Halal Chicken Substitute)',
    cuisine: 'Chinese',
    ingredients: [
      'chicken',
      'pineapple',
      'bell peppers',
      'vinegar',
      'ketchup',
      'sugar',
    ],
    recipeSteps: [
      'Fry chicken until crispy.',
      'Toss in sweet and sour sauce with veggies.',
    ],
    allergies: [],
  },
  {
    name: 'Char Siu (Halal Chicken)',
    cuisine: 'Chinese',
    ingredients: [
      'chicken thighs',
      'hoisin sauce',
      'honey',
      'soy sauce',
      'five-spice powder',
    ],
    recipeSteps: [
      'Marinate chicken in sauce mixture for 2 hours.',
      'Roast at 375°F (190°C) until caramelized.',
    ],
    allergies: ['soy'],
  },
  {
    name: 'Dan Dan Noodles',
    cuisine: 'Chinese',
    ingredients: [
      'noodles',
      'ground pork',
      'chili oil',
      'peanuts',
      'soy sauce',
    ],
    recipeSteps: [
      'Cook noodles. Sauté meat with chili oil and soy sauce.',
      'Top noodles with meat and crushed peanuts.',
    ],
    allergies: ['nuts', 'gluten', 'soy'],
  },
  {
    name: 'Egg Drop Soup',
    cuisine: 'Chinese',
    ingredients: [
      'chicken broth',
      'eggs',
      'cornstarch',
      'green onions',
      'sesame oil',
    ],
    recipeSteps: [
      'Bring broth to a boil. Stir in cornstarch slurry.',
      'Drizzle beaten eggs into broth while stirring.',
    ],
    allergies: ['eggs'],
  },
  {
    name: 'Peking Duck',
    cuisine: 'Chinese',
    ingredients: [
      'duck (Halal chicken)',
      'hoisin sauce',
      'pancakes',
      'cucumber',
      'green onions',
    ],
    recipeSteps: [
      'Roast duck until crispy. Slice thinly.',
      'Serve with pancakes, hoisin, and veggies.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Sesame Chicken',
    cuisine: 'Chinese',
    ingredients: [
      'chicken',
      'soy sauce',
      'honey',
      'sesame seeds',
      'cornstarch',
    ],
    recipeSteps: [
      'Coat chicken in cornstarch. Fry until crispy.',
      'Toss in honey-soy sauce. Sprinkle sesame seeds.',
    ],
    allergies: ['soy'],
  },
  {
    name: 'Beef and Broccoli',
    cuisine: 'Chinese',
    ingredients: ['beef', 'broccoli', 'soy sauce', 'oyster sauce', 'garlic'],
    recipeSteps: [
      'Stir-fry beef and garlic. Add broccoli.',
      'Toss with sauces and simmer.',
    ],
    allergies: ['soy'],
  },
  {
    name: 'Lo Mein',
    cuisine: 'Chinese',
    ingredients: [
      'egg noodles',
      'shrimp (Halal chicken)',
      'bok choy',
      'soy sauce',
      'sesame oil',
    ],
    recipeSteps: [
      'Cook noodles. Stir-fry shrimp and veggies.',
      'Toss noodles with soy sauce and oil.',
    ],
    allergies: ['gluten', 'soy', 'shellfish'],
  },
  {
    name: 'Scallion Pancakes',
    cuisine: 'Chinese',
    ingredients: ['flour', 'scallions', 'salt', 'oil'],
    recipeSteps: [
      'Make dough with flour and water. Roll with scallions.',
      'Pan-fry until crispy.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Red Bean Buns',
    cuisine: 'Chinese',
    ingredients: ['flour', 'red bean paste', 'yeast', 'sugar'],
    recipeSteps: [
      'Proof dough. Fill with red bean paste.',
      'Steam for 15 minutes.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Zongzi',
    cuisine: 'Chinese',
    ingredients: [
      'glutinous rice',
      'bamboo leaves',
      'pork (Halal chicken)',
      'mushrooms',
    ],
    recipeSteps: [
      'Soak rice and leaves. Layer rice and filling in leaves.',
      'Steam for 2 hours.',
    ],
    allergies: [],
  },
  {
    name: 'Ma Po Eggplant',
    cuisine: 'Chinese',
    ingredients: [
      'eggplant',
      'ground pork',
      'chili paste',
      'soy sauce',
      'garlic',
    ],
    recipeSteps: [
      'Sauté pork and garlic. Add eggplant and chili paste.',
      'Simmer until tender.',
    ],
    allergies: ['soy'],
  },
  {
    name: 'Bulgogi',
    cuisine: 'Korean',
    ingredients: ['beef', 'soy sauce', 'sesame oil', 'garlic', 'pear juice'],
    recipeSteps: [
      'Marinate beef in soy sauce, pear juice, and spices.',
      'Grill or pan-fry until caramelized.',
    ],
    allergies: ['soy'],
  },
  {
    name: 'Kimchi Fried Rice',
    cuisine: 'Korean',
    ingredients: ['rice', 'kimchi', 'spam', 'eggs', 'sesame oil'],
    recipeSteps: [
      'Sauté kimchi and spam. Add rice.',
      'Top with fried egg and sesame oil.',
    ],
    allergies: ['eggs'],
  },
  {
    name: 'Japchae',
    cuisine: 'Korean',
    ingredients: [
      'sweet potato noodles',
      'beef',
      'spinach',
      'carrots',
      'soy sauce',
    ],
    recipeSteps: [
      'Boil noodles. Stir-fry veggies and beef.',
      'Toss with soy sauce and sesame oil.',
    ],
    allergies: ['soy'],
  },
  {
    name: 'Tteokbokki',
    cuisine: 'Korean',
    ingredients: ['rice cakes', 'gochujang', 'fish cakes', 'hard-boiled eggs'],
    recipeSteps: [
      'Simmer rice cakes in spicy sauce.',
      'Add fish cakes and eggs.',
    ],
    allergies: ['eggs'],
  },
  {
    name: 'Bibimbap',
    cuisine: 'Korean',
    ingredients: [
      'rice',
      'beef',
      'spinach',
      'carrots',
      'fried egg',
      'gochujang',
    ],
    recipeSteps: [
      'Arggle veggies and beef over rice.',
      'Top with egg and gochujang. Mix before eating.',
    ],
    allergies: ['eggs'],
  },
  {
    name: 'Korean Fried Chicken',
    cuisine: 'Korean',
    ingredients: [
      'chicken wings',
      'gochujang',
      'honey',
      'garlic',
      'cornstarch',
    ],
    recipeSteps: [
      'Coat chicken in cornstarch. Fry until crispy.',
      'Toss in spicy-sweet sauce.',
    ],
    allergies: [],
  },
  {
    name: 'Haemul Pajeon (Halal Vegetable Pancake)',
    cuisine: 'Korean',
    ingredients: [
      'flour',
      'scallions',
      'zucchini',
      'carrots',
      'soy dipping sauce',
    ],
    recipeSteps: [
      'Mix batter with veggies. Pan-fry until crispy.',
      'Serve with dipping sauce.',
    ],
    allergies: ['gluten', 'soy'],
  },
  {
    name: 'Sundubu Jjigae',
    cuisine: 'Korean',
    ingredients: ['soft tofu', 'clams', 'kimchi', 'eggs', 'gochugaru'],
    recipeSteps: [
      'Simmer tofu and kimchi in broth.',
      'Crack egg into stew before serving.',
    ],
    allergies: ['eggs', 'shellfish'],
  },
  {
    name: 'Gimbap',
    cuisine: 'Korean',
    ingredients: ['seaweed sheets', 'rice', 'spinach', 'carrots', 'beef'],
    recipeSteps: [
      'Layer rice and veggies on seaweed. Roll tightly.',
      'Slice into bite-sized pieces.',
    ],
    allergies: [],
  },
  {
    name: 'Mandu (Dumplings)',
    cuisine: 'Korean',
    ingredients: [
      'dumpling wrappers',
      'ground pork (Halal chicken)',
      'tofu',
      'garlic',
      'soy sauce',
    ],
    recipeSteps: [
      'Fill wrappers with meat and tofu mixture.',
      'Steam or pan-fry until cooked.',
    ],
    allergies: ['gluten', 'soy'],
  },

  {
    name: 'Samosas',
    cuisine: 'Snacks',
    ingredients: ['potatoes', 'peas', 'spices', 'wrappers', 'oil'],
    recipeSteps: [
      'Fill wrappers with spiced potato mix.',
      'Deep-fry until golden.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Spring Rolls',
    cuisine: 'Snacks',
    ingredients: [
      'spring roll wrappers',
      'cabbage',
      'carrots',
      'vermicelli',
      'mushrooms',
    ],
    recipeSteps: [
      'Sauté veggies. Fill wrappers and roll.',
      'Deep-fry until crispy.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Popcorn Chicken',
    cuisine: 'Snacks',
    ingredients: ['chicken bites', 'flour', 'paprika', 'garlic powder', 'oil'],
    recipeSteps: [
      'Coat chicken in seasoned flour.',
      'Deep-fry until golden and crispy.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Fruit Chaat',
    cuisine: 'Snacks',
    ingredients: [
      'apples',
      'bananas',
      'oranges',
      'chaat masala',
      'lemon juice',
    ],
    recipeSteps: ['Chop fruits. Toss with chaat masala and lemon juice.'],
    allergies: [],
  },
  {
    name: 'Cheese Sticks',
    cuisine: 'Snacks',
    ingredients: ['puff pastry', 'cheddar cheese', 'paprika', 'egg wash'],
    recipeSteps: [
      'Cut pastry into strips. Top with cheese and paprika.',
      'Bake at 400°F (200°C) for 15 minutes.',
    ],
    allergies: ['dairy', 'gluten'],
  },
  {
    name: 'Veggie Pakora',
    cuisine: 'Snacks',
    ingredients: [
      'chickpea flour',
      'onions',
      'spinach',
      'green chilies',
      'oil',
    ],
    recipeSteps: [
      'Mix veggies with flour and water to make batter.',
      'Deep-fry spoonfuls until crispy.',
    ],
    allergies: [],
  },
  {
    name: 'Chicken Wings',
    cuisine: 'Snacks',
    ingredients: ['chicken wings', 'hot sauce', 'butter', 'garlic powder'],
    recipeSteps: [
      'Bake wings at 425°F (220°C) for 40 minutes.',
      'Toss in hot sauce mixture.',
    ],
    allergies: ['dairy'],
  },
  {
    name: 'Potato Wedges',
    cuisine: 'Snacks',
    ingredients: ['potatoes', 'paprika', 'garlic powder', 'olive oil'],
    recipeSteps: [
      'Cut potatoes into wedges. Toss with oil and spices.',
      'Bake at 425°F (220°C) for 25 minutes.',
    ],
    allergies: [],
  },
  {
    name: 'Banana Fritters',
    cuisine: 'Snacks',
    ingredients: ['bananas', 'flour', 'sugar', 'oil'],
    recipeSteps: [
      'Dip banana slices in batter.',
      'Deep-fry until golden. Dust with sugar.',
    ],
    allergies: ['gluten'],
  },
  {
    name: 'Stuffed Dates',
    cuisine: 'Snacks',
    ingredients: ['dates', 'almonds', 'cream cheese'],
    recipeSteps: ['Remove date pits. Stuff with almond and cream cheese.'],
    allergies: ['nuts', 'dairy'],
  },
];
