export const recipes = [
  // Chicken Biryani Recipe
  {
    id: 0,
    name: 'Chicken Biryani',
    cuisine: 'Pakistani',
    servings: 1,
    image:
      'https://drive.google.com/file/d/1yny_AToin-LCsMBVlf8cNzG2EuczJzA7/view?usp=drive_link',
    ingredients: [
      {name: 'basmati rice', quantity: '2 cups (400g), soaked 30 mins'},
      {name: 'chicken', quantity: '1 kg, bone-in pieces'},
      {name: 'yogurt', quantity: '1/2 cup (120ml)'},
      {name: 'ginger-garlic paste', quantity: '2 tbsp (30g)'},
      {name: 'biryani masala', quantity: '3 tbsp (45g)'},
      {name: 'onions', quantity: '2 large, thinly sliced'},
      {name: 'cooking oil', quantity: '3/4 cup (180ml)'},
      {name: 'saffron', quantity: '1/4 tsp, soaked in 2 tbsp warm milk'},
      {name: 'fried onions', quantity: '1/2 cup (optional garnish)'},
      {name: 'fresh coriander', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Marinate Chicken',
        details: [
          'In large bowl, mix:',
          '- Yogurt (1/2 cup)',
          '- Ginger-garlic paste (2 tbsp)',
          '- Biryani masala (2 tbsp)',
          '- Salt (1.5 tsp)',
          'Add chicken pieces, coat thoroughly',
          'Refrigerate for 2+ hours (overnight best)',
        ],
      },
      {
        step: 2,
        title: 'Prepare Rice & Onions',
        details: [
          'Heat oil (1/4 cup) in pan',
          'Fry sliced onions until golden brown (8-10 mins)',
          'Drain and set aside',
          'Boil rice in 4 cups water with:',
          '- Salt (1 tsp)',
          '- Cumin seeds (1 tsp)',
          'Cook until 70% done (~5 mins)',
          'Drain and layer on marinated chicken',
        ],
      },
      {
        step: 3,
        title: 'Layering & Dum Cooking',
        details: [
          'In heavy-bottomed pot:',
          '1. Layer 1: Marinated chicken',
          '2. Layer 2: Parboiled rice',
          '3. Sprinkle saffron milk & fried onions',
          '4. Add 2 tbsp ghee (optional)',
          'Seal lid with dough or heavy weight',
          'Cook on LOW heat for 25-30 mins',
          'Let rest 10 mins before opening',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Gently mix layers before serving',
          'Garnish with:',
          '- Fresh coriander',
          '- Fried onions',
          '- Lemon wedges',
          'Serve with raita or salad',
        ],
      },
    ],
    allergies: ['dairy'],
    cookingTime: '2 hrs 30 mins (incl. marination)',
    difficulty: 'Intermediate',
  },
  // Nihari Recipe
  {
    id: 1,
    name: 'Nihari',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1SocrZYgneJflFHkeaJbhXzxmf9MMxfPm/view?usp=sharing',
    servings: 6,
    ingredients: [
      {name: 'beef', quantity: '1 kg, bone-in pieces'},
      {name: 'yogurt', quantity: '1 cup (240ml)'},
      {name: 'ginger-garlic', quantity: '2 tbsp (30g)'},
      {name: 'onions', quantity: '2 large, thinly sliced'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'redchili', quantity: '2 tbsp powder'},
      {name: 'coriander', quantity: '2 tbsp powder'},
      {name: 'turmeric', quantity: '1 tsp'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/2 cup (120ml)'},
      {name: 'ghee', quantity: '2 tbsp (optional)'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Marinate Beef',
        details: [
          'In large bowl, mix:',
          '- Yogurt (1 cup)',
          '- Ginger-garlic (2 tbsp)',
          '- Red chili powder (1 tbsp)',
          '- Coriander powder (1 tbsp)',
          '- Turmeric (1/2 tsp)',
          '- Salt (1.5 tsp)',
          'Add beef pieces, coat thoroughly',
          'Refrigerate for 2+ hours (overnight best)',
        ],
      },
      {
        step: 2,
        title: 'Prepare Nihari',
        details: [
          'Heat oil (1/4 cup) in large pot',
          'Fry sliced onions until golden brown (8-10 mins)',
          'Add marinated beef, cook until browned (5-7 mins)',
          'Add chopped tomatoes, cook until softened (3-5 mins)',
          'Add remaining spices:',
          '- Red chili powder (1 tbsp)',
          '- Coriander powder (1 tbsp)',
          '- Turmeric (1/2 tsp)',
          '- Garam masala (1 tsp)',
          'Cook for 2-3 mins',
        ],
      },
      {
        step: 3,
        title: 'Slow Cooking',
        details: [
          'Add 4 cups water, bring to boil',
          'Reduce heat, cover, and simmer for 2-3 hours',
          'Stir occasionally until beef is tender',
          'Add ghee (optional) for richness',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Ginger juliennes',
          '- Lemon wedges',
          'Serve with naan or rice',
        ],
      },
    ],
    allergies: ['dairy'],
    cookingTime: '3 hrs 30 mins (incl. marination)',
    difficulty: 'Intermediate',
  },
  // Daal Chawal Recipe
  {
    id: 2,
    name: 'Daal Chawal',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1Qbz3gf5wBlm4SfKEZ8nIePbJDDkHCaug/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'rice', quantity: '2 cups (400g), soaked 30 mins'},
      {
        name: 'lentils',
        quantity: '1 cup (200g), split (e.g., moong or masoor)',
      },
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'turmeric', quantity: '1 tsp'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Lentils',
        details: [
          'Rinse lentils thoroughly',
          'Soak in water for 30 mins, then drain',
        ],
      },
      {
        step: 2,
        title: 'Cook Daal',
        details: [
          'Heat oil in pot, add cumin seeds',
          'Fry until fragrant (1 min)',
          'Add chopped onions, cook until golden (5 mins)',
          'Add ginger-garlic, cook for 1 min',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add lentils, turmeric, red chili powder',
          'Cook for 2 mins',
          'Add 3 cups water, bring to boil',
          'Reduce heat, cover, and simmer for 20-25 mins',
          'Stir occasionally until lentils are tender',
        ],
      },
      {
        step: 3,
        title: 'Cook Rice',
        details: [
          'Boil rice in 4 cups water with salt (1 tsp)',
          'Cook until tender (15-20 mins)',
          'Drain excess water',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Serve daal over rice',
          'Garnish with:',
          '- Cilantro',
          '- Lemon wedges',
          'Serve with yogurt or pickle',
        ],
      },
    ],
    allergies: [],
    cookingTime: '1 hr 15 mins',
    difficulty: 'Easy',
  },
  // Seekh Kebabs Recipe
  {
    id: 3,
    name: 'Seekh Kebabs',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1D1Cqi4B3MQ3FhIwl2rJUO8nAARGvkCh5/view?usp=sharing',
    servings: 6,
    ingredients: [
      {name: 'mutton', quantity: '500g, minced'},
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'greenchili', quantity: '2, finely chopped'},
      {name: 'coriander', quantity: '1/4 cup chopped'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cumin', quantity: '1 tsp powder'},
      {name: 'oil', quantity: '2 tbsp (30ml)'},
      {name: 'lemon', quantity: '1, juiced'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Kebab Mixture',
        details: [
          'In bowl, combine:',
          '- Minced mutton',
          '- Chopped onions',
          '- Ginger-garlic',
          '- Green chili',
          '- Chopped coriander',
          '- Garam masala',
          '- Cumin powder',
          '- Salt (1 tsp)',
          'Mix well until fully incorporated',
        ],
      },
      {
        step: 2,
        title: 'Shape Kebabs',
        details: [
          'Divide mixture into equal portions',
          'Shape each portion around skewers',
          'Press firmly to ensure mixture sticks',
        ],
      },
      {
        step: 3,
        title: 'Cook Kebabs',
        details: [
          'Preheat grill or pan to medium-high heat',
          'Brush with oil',
          'Cook kebabs, turning occasionally, for 8-10 mins',
          'Ensure even browning and cook until done',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Drizzle with lemon juice',
          'Serve with naan or paratha',
          'Accompany with mint chutney or raita',
        ],
      },
    ],
    allergies: [],
    cookingTime: '45 mins',
    difficulty: 'Easy',
  },
  // Haleem Recipe
  {
    id: 4,
    name: 'Haleem',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1M6BJgBImAiUM74vgfKwiVDDJnzFAWGkv/view?usp=sharing',
    servings: 8,
    ingredients: [
      {name: 'mutton', quantity: '500g, bone-in pieces'},
      {name: 'wheat', quantity: '1/2 cup (100g), cracked'},
      {name: 'lentils', quantity: '1/2 cup (100g), split (e.g., chana daal)'},
      {name: 'barley', quantity: '1/4 cup (50g)'},
      {name: 'onions', quantity: '2 large, thinly sliced'},
      {name: 'ginger-garlic', quantity: '2 tbsp (30g)'},
      {name: 'turmeric', quantity: '1 tsp'},
      {name: 'redchili', quantity: '2 tbsp powder'},
      {name: 'coriander', quantity: '2 tbsp powder'},
      {name: 'oil', quantity: '1/2 cup (120ml)'},
      {name: 'ghee', quantity: '2 tbsp (optional)'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Ingredients',
        details: [
          'Soak wheat, lentils, and barley separately for 1 hour',
          'Drain and set aside',
        ],
      },
      {
        step: 2,
        title: 'Cook Mutton',
        details: [
          'Heat oil in large pot',
          'Fry sliced onions until golden brown (8-10 mins)',
          'Add mutton, cook until browned (5-7 mins)',
          'Add ginger-garlic, cook for 1 min',
          'Add turmeric, red chili powder, coriander powder',
          'Cook for 2-3 mins',
        ],
      },
      {
        step: 3,
        title: 'Combine & Cook',
        details: [
          'Add soaked wheat, lentils, and barley to pot',
          'Add 6 cups water, bring to boil',
          'Reduce heat, cover, and simmer for 2-3 hours',
          'Stir occasionally until mixture thickens',
          'Blend until smooth (optional)',
          'Add ghee (optional) for richness',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Ginger juliennes',
          '- Lemon wedges',
          'Serve with naan or roti',
        ],
      },
    ],
    allergies: ['gluten', 'dairy'],
    cookingTime: '3 hrs 30 mins',
    difficulty: 'Intermediate',
  },
  // Chicken Karahi Recipe
  {
    id: 5,
    name: 'Chicken Karahi',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1Tkqq9qW_fCCLfnWuf9PpgYdr-LzbYFYr/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'chicken', quantity: '500g, bone-in pieces'},
      {name: 'tomatoes', quantity: '3 medium, chopped'},
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'greenchili', quantity: '2, sliced'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Chicken',
        details: [
          'Heat oil in large pan',
          'Add chicken pieces, cook until browned (5-7 mins)',
          'Remove chicken from pan, set aside',
        ],
      },
      {
        step: 2,
        title: 'Cook Karahi',
        details: [
          'In same pan, add cumin seeds',
          'Fry until fragrant (1 min)',
          'Add chopped onions, cook until golden (5 mins)',
          'Add ginger-garlic, cook for 1 min',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add red chili powder, coriander powder',
          'Cook for 2 mins',
          'Return chicken to pan, mix well',
        ],
      },
      {
        step: 3,
        title: 'Simmer',
        details: [
          'Add 1/2 cup water, bring to boil',
          'Reduce heat, cover, and simmer for 20-25 mins',
          'Stir occasionally until chicken is tender',
          'Sprinkle garam masala, mix well',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Green chili',
          '- Lemon wedges',
          'Serve with naan or rice',
        ],
      },
    ],
    allergies: [],
    cookingTime: '1 hr',
    difficulty: 'Easy',
  },
  {
    id: 6,
    name: 'Aloo Gosht',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1i6LUroyKZYME_D-6X02vbG9xv1mg4plt/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'mutton', quantity: '500g, bone-in pieces'},
      {name: 'potatoes', quantity: '2 medium, cubed'},
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'turmeric', quantity: '1/2 tsp'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Mutton',
        details: [
          'Heat oil in large pan',
          'Add mutton pieces, cook until browned (5-7 mins)',
          'Remove mutton from pan, set aside',
        ],
      },
      {
        step: 2,
        title: 'Cook Aloo Gosht',
        details: [
          'In same pan, add cumin seeds',
          'Fry until fragrant (1 min)',
          'Add chopped onions, cook until golden (5 mins)',
          'Add ginger-garlic, cook for 1 min',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add red chili powder, coriander powder, turmeric',
          'Cook for 2 mins',
          'Return mutton to pan, add potatoes',
          'Mix well',
        ],
      },
      {
        step: 3,
        title: 'Simmer',
        details: [
          'Add 1 cup water, bring to boil',
          'Reduce heat, cover, and simmer for 25-30 mins',
          'Stir occasionally until mutton and potatoes are tender',
          'Sprinkle garam masala, mix well',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Green chili',
          '- Lemon wedges',
          'Serve with naan or rice',
        ],
      },
    ],
    allergies: [],
    cookingTime: '1 hr 15 mins',
    difficulty: 'Easy',
  },

  // Chapli Kebabs Recipe
  {
    id: 7,
    name: 'Chapli Kebabs',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1R_MBwLS7BwarcSnBx_N6d1e0zr0myWzI/view?usp=sharing',
    servings: 6,
    ingredients: [
      {name: 'beef', quantity: '500g, minced'},
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'tomatoes', quantity: '1 medium, finely chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'greenchili', quantity: '2, finely chopped'},
      {name: 'coriander', quantity: '1/4 cup chopped'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cumin', quantity: '1 tsp powder'},
      {name: 'oil', quantity: '2 tbsp (30ml)'},
      {name: 'lemon', quantity: '1, juiced'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Kebab Mixture',
        details: [
          'In bowl, combine:',
          '- Minced beef',
          '- Chopped onions',
          '- Chopped tomatoes',
          '- Ginger-garlic',
          '- Green chili',
          '- Chopped coriander',
          '- Garam masala',
          '- Cumin powder',
          '- Salt (1 tsp)',
          'Mix well until fully incorporated',
        ],
      },
      {
        step: 2,
        title: 'Shape Kebabs',
        details: [
          'Divide mixture into equal portions',
          'Flatten each portion into a round patty',
          'Press firmly to ensure mixture sticks',
        ],
      },
      {
        step: 3,
        title: 'Cook Kebabs',
        details: [
          'Heat oil in pan over medium heat',
          'Cook kebabs, turning occasionally, for 6-8 mins',
          'Ensure even browning and cook until done',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Drizzle with lemon juice',
          'Serve with naan or paratha',
          'Accompany with mint chutney or raita',
        ],
      },
    ],
    allergies: [],
    cookingTime: '45 mins',
    difficulty: 'Easy',
  },

  // Beef Pulao Recipe
  {
    id: 8,
    name: 'Beef Pulao',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/18slBbvbP4PDaov4Agr_3sdfj4jmrxZk9/view?usp=sharing',
    servings: 6,
    ingredients: [
      {name: 'rice', quantity: '2 cups (400g), soaked 30 mins'},
      {name: 'beef', quantity: '500g, bone-in pieces'},
      {name: 'onions', quantity: '2 medium, thinly sliced'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'yogurt', quantity: '1/2 cup (120ml)'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Marinate Beef',
        details: [
          'In bowl, mix:',
          '- Yogurt (1/2 cup)',
          '- Ginger-garlic (1 tbsp)',
          '- Red chili powder (1/2 tsp)',
          '- Coriander powder (1/2 tsp)',
          '- Salt (1 tsp)',
          'Add beef pieces, coat thoroughly',
          'Set aside for 30 mins',
        ],
      },
      {
        step: 2,
        title: 'Prepare Rice & Beef',
        details: [
          'Heat oil in large pan',
          'Fry sliced onions until golden brown (8-10 mins)',
          'Add marinated beef, cook until browned (5-7 mins)',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add remaining spices:',
          '- Red chili powder (1/2 tsp)',
          '- Coriander powder (1/2 tsp)',
          '- Cumin (1 tsp)',
          'Cook for 2 mins',
        ],
      },
      {
        step: 3,
        title: 'Cook Rice',
        details: [
          'Add 4 cups water, bring to boil',
          'Add soaked rice, stir gently',
          'Reduce heat, cover, and simmer for 15-20 mins',
          'Cook until rice is tender and water is absorbed',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Fried onions',
          '- Lemon wedges',
          'Serve with raita or salad',
        ],
      },
    ],
    allergies: [],
    cookingTime: '1 hr 30 mins',
    difficulty: 'Intermediate',
  },

  // Chicken Tikka Recipe
  {
    id: 9,
    name: 'Chicken Tikka',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1RbBqvseJdnSrNiG28Ipg6B4SaA48azeO/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'chicken', quantity: '500g, boneless pieces'},
      {name: 'yogurt', quantity: '1/2 cup (120ml)'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'lemon', quantity: '1, juiced'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'oil', quantity: '2 tbsp (30ml)'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Marinate Chicken',
        details: [
          'In bowl, mix:',
          '- Yogurt (1/2 cup)',
          '- Ginger-garlic (1 tbsp)',
          '- Lemon juice (1 tbsp)',
          '- Red chili powder (1/2 tsp)',
          '- Coriander powder (1/2 tsp)',
          '- Garam masala (1/2 tsp)',
          '- Salt (1 tsp)',
          'Add chicken pieces, coat thoroughly',
          'Refrigerate for 2+ hours (overnight best)',
        ],
      },
      {
        step: 2,
        title: 'Grill Chicken',
        details: [
          'Preheat grill or oven to medium-high heat',
          'Thread chicken onto skewers',
          'Brush with oil',
          'Grill for 10-12 mins, turning occasionally',
          'Ensure even browning and cook until done',
        ],
      },
      {
        step: 3,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Lemon wedges',
          'Serve with naan or salad',
        ],
      },
    ],
    allergies: ['dairy'],
    cookingTime: '2 hrs 30 mins (incl. marination)',
    difficulty: 'Easy',
  },

  // Chana Masala Recipe
  {
    id: 10,
    name: 'Chana Masala',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/12tVYBn6dPcCniUpRgqYkQsjGEVyKGaIC/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'chickpeas', quantity: '2 cups (400g), soaked overnight'},
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'turmeric', quantity: '1/2 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Chickpeas',
        details: ['Drain and rinse soaked chickpeas', 'Set aside'],
      },
      {
        step: 2,
        title: 'Cook Chana Masala',
        details: [
          'Heat oil in pan, add cumin seeds',
          'Fry until fragrant (1 min)',
          'Add chopped onions, cook until golden (5 mins)',
          'Add ginger-garlic, cook for 1 min',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add red chili powder, coriander powder, turmeric',
          'Cook for 2 mins',
          'Add chickpeas, mix well',
        ],
      },
      {
        step: 3,
        title: 'Simmer',
        details: [
          'Add 2 cups water, bring to boil',
          'Reduce heat, cover, and simmer for 20-25 mins',
          'Stir occasionally until chickpeas are tender',
          'Sprinkle garam masala, mix well',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Lemon wedges',
          'Serve with naan or rice',
        ],
      },
    ],
    allergies: [],
    cookingTime: '1 hr 15 mins',
    difficulty: 'Easy',
  },

  // Aloo Paratha Recipe
  {
    id: 11,
    name: 'Aloo Paratha',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/11oQYxI61R7vkjTsKhjT3scvdmztloul4/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'wheat', quantity: '2 cups (250g) flour'},
      {name: 'potatoes', quantity: '2 medium, boiled and mashed'},
      {name: 'onions', quantity: '1 small, finely chopped'},
      {name: 'greenchili', quantity: '1, finely chopped'},
      {name: 'coriander', quantity: '1/4 cup chopped'},
      {name: 'cumin', quantity: '1 tsp powder'},
      {name: 'garammasala', quantity: '1/2 tsp'},
      {name: 'oil', quantity: '2 tbsp (30ml)'},
      {name: 'ghee', quantity: '2 tbsp (optional)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Dough',
        details: [
          'In bowl, combine:',
          '- Wheat flour',
          '- Salt (1/2 tsp)',
          '- Water (as needed)',
          'Knead into smooth dough',
          'Set aside for 10 mins',
        ],
      },
      {
        step: 2,
        title: 'Prepare Filling',
        details: [
          'In bowl, mix:',
          '- Mashed potatoes',
          '- Chopped onions',
          '- Green chili',
          '- Chopped coriander',
          '- Cumin powder',
          '- Garam masala',
          '- Salt (1/2 tsp)',
          'Mix well',
        ],
      },
      {
        step: 3,
        title: 'Assemble Paratha',
        details: [
          'Divide dough into equal portions',
          'Roll each portion into a small circle',
          'Place filling in center, fold dough over to enclose',
          'Roll out gently into a flat disc',
        ],
      },
      {
        step: 4,
        title: 'Cook Paratha',
        details: [
          'Heat oil or ghee in pan over medium heat',
          'Cook paratha until golden brown on both sides (2-3 mins each side)',
        ],
      },
      {
        step: 5,
        title: 'Serving',
        details: ['Serve hot with yogurt or pickle'],
      },
    ],
    allergies: ['gluten', 'dairy'],
    cookingTime: '45 mins',
    difficulty: 'Easy',
  },

  // Saag Recipe
  {
    id: 12,
    name: 'Saag',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/118Sc2fu3r8AtXKVD2SyxMIQNq8Oru1Ia/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'spinach', quantity: '1 bunch, chopped'},
      {name: 'mustard', quantity: '1 bunch, chopped'},
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'greenchili', quantity: '2, sliced'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cream', quantity: '2 tbsp (optional)'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Greens',
        details: ['Wash and chop spinach and mustard greens', 'Set aside'],
      },
      {
        step: 2,
        title: 'Cook Saag',
        details: [
          'Heat oil in pan, add cumin seeds',
          'Fry until fragrant (1 min)',
          'Add chopped onions, cook until golden (5 mins)',
          'Add ginger-garlic, cook for 1 min',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add red chili powder, coriander powder',
          'Cook for 2 mins',
          'Add chopped greens, mix well',
        ],
      },
      {
        step: 3,
        title: 'Simmer',
        details: [
          'Add 1/2 cup water, bring to boil',
          'Reduce heat, cover, and simmer for 15-20 mins',
          'Stir occasionally until greens are tender',
          'Stir in cream (optional) for richness',
          'Sprinkle garam masala, mix well',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Green chili',
          'Serve with roti or rice',
        ],
      },
    ],
    allergies: ['dairy'],
    cookingTime: '1 hr',
    difficulty: 'Easy',
  },

  // Kheer Recipe
  {
    id: 13,
    name: 'Kheer',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1WVSd6mw2gY8JiKqw40Q0WcZC1-TuFJ3d/view?usp=sharing',
    servings: 6,
    ingredients: [
      {name: 'rice', quantity: '1/2 cup (100g), basmati'},
      {name: 'milk', quantity: '1 liter (4 cups)'},
      {name: 'sugar', quantity: '1/2 cup (100g)'},
      {name: 'cardamom', quantity: '4-5 pods'},
      {name: 'almonds', quantity: '1/4 cup (30g), sliced'},
      {name: 'raisins', quantity: '1/4 cup (40g)'},
      {name: 'ghee', quantity: '1 tbsp (15ml)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Rice',
        details: [
          'Rinse rice thoroughly',
          'Soak in water for 30 mins, then drain',
        ],
      },
      {
        step: 2,
        title: 'Cook Kheer',
        details: [
          'In large pot, bring milk to boil',
          'Add soaked rice, reduce heat to low',
          'Cook, stirring occasionally, until rice is tender (20-25 mins)',
          'Add sugar, cardamom pods, mix well',
        ],
      },
      {
        step: 3,
        title: 'Add Nuts',
        details: [
          'In small pan, heat ghee',
          'Fry almonds and raisins until golden (1-2 mins)',
          'Add to kheer, mix well',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: ['Serve chilled, garnished with additional nuts'],
      },
    ],
    allergies: ['dairy', 'nuts'],
    cookingTime: '1 hr',
    difficulty: 'Easy',
  },

  // Chicken Handi Recipe
  {
    id: 14,
    name: 'Chicken Handi',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1jYCiTFy39wdqwIADK5sgDuAjPNTeDuwB/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'chicken', quantity: '500g, bone-in pieces'},
      {name: 'onions', quantity: '2 medium, thinly sliced'},
      {name: 'tomatoes', quantity: '3 medium, chopped'},
      {name: 'yogurt', quantity: '1/2 cup (120ml)'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Marinate Chicken',
        details: [
          'In bowl, mix:',
          '- Yogurt (1/2 cup)',
          '- Ginger-garlic (1 tbsp)',
          '- Red chili powder (1/2 tsp)',
          '- Coriander powder (1/2 tsp)',
          '- Salt (1 tsp)',
          'Add chicken pieces, coat thoroughly',
          'Set aside for 30 mins',
        ],
      },
      {
        step: 2,
        title: 'Cook Chicken Handi',
        details: [
          'Heat oil in large pan',
          'Fry sliced onions until golden brown (8-10 mins)',
          'Add marinated chicken, cook until browned (5-7 mins)',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add remaining spices:',
          '- Red chili powder (1/2 tsp)',
          '- Coriander powder (1/2 tsp)',
          '- Cumin (1 tsp)',
          'Cook for 2 mins',
        ],
      },
      {
        step: 3,
        title: 'Simmer',
        details: [
          'Add 1/2 cup water, bring to boil',
          'Reduce heat, cover, and simmer for 20-25 mins',
          'Stir occasionally until chicken is tender',
          'Sprinkle garam masala, mix well',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Green chili',
          '- Lemon wedges',
          'Serve with naan or rice',
        ],
      },
    ],
    allergies: ['dairy'],
    cookingTime: '1 hr 15 mins',
    difficulty: 'Easy',
  },

  // Beef Kofta Recipe
  {
    id: 15,
    name: 'Beef Kofta',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1qTFBjhWuTsAxMwD86ddiuKMo601pUFl_/view?usp=sharing',
    servings: 6,
    ingredients: [
      {name: 'beef', quantity: '500g, minced'},
      {name: 'onions', quantity: '1 medium, finely chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'greenchili', quantity: '2, finely chopped'},
      {name: 'coriander', quantity: '1/4 cup chopped'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cumin', quantity: '1 tsp powder'},
      {name: 'oil', quantity: '2 tbsp (30ml)'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'turmeric', quantity: '1/2 tsp'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Kofta Mixture',
        details: [
          'In bowl, combine:',
          '- Minced beef',
          '- Chopped onions',
          '- Ginger-garlic',
          '- Green chili',
          '- Chopped coriander',
          '- Garam masala',
          '- Cumin powder',
          '- Salt (1 tsp)',
          'Mix well until fully incorporated',
        ],
      },
      {
        step: 2,
        title: 'Shape Koftas',
        details: [
          'Divide mixture into equal portions',
          'Shape each portion into a small ball',
          'Flatten slightly',
        ],
      },
      {
        step: 3,
        title: 'Cook Koftas',
        details: [
          'Heat oil in pan over medium heat',
          'Cook koftas, turning occasionally, for 6-8 mins',
          'Ensure even browning and cook until done',
          'Remove koftas from pan, set aside',
        ],
      },
      {
        step: 4,
        title: 'Prepare Gravy',
        details: [
          'In same pan, add chopped tomatoes',
          'Cook until softened (3 mins)',
          'Add red chili powder, turmeric',
          'Cook for 2 mins',
          'Add 1 cup water, bring to boil',
          'Return koftas to pan, mix well',
          'Simmer for 10-15 mins',
        ],
      },
      {
        step: 5,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Green chili',
          'Serve with naan or rice',
        ],
      },
    ],
    allergies: [],
    cookingTime: '1 hr',
    difficulty: 'Easy',
  },

  // Gajar ka Halwa Recipe
  {
    id: 16,
    name: 'Gajar ka Halwa',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/15rRhW28ksm9xeTd89xH5eKkjrtrIFgub/view?usp=sharing',
    servings: 6,
    ingredients: [
      {name: 'carrots', quantity: '1 kg, grated'},
      {name: 'milk', quantity: '1 liter (4 cups)'},
      {name: 'sugar', quantity: '1 cup (200g)'},
      {name: 'ghee', quantity: '1/4 cup (60ml)'},
      {name: 'cardamom', quantity: '4-5 pods'},
      {name: 'almonds', quantity: '1/4 cup (30g), sliced'},
      {name: 'raisins', quantity: '1/4 cup (40g)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Carrots',
        details: ['Wash, peel, and grate carrots', 'Set aside'],
      },
      {
        step: 2,
        title: 'Cook Halwa',
        details: [
          'In large pan, heat ghee',
          'Add grated carrots, sauté for 5 mins',
          'Add milk, bring to boil',
          'Reduce heat, cook until carrots are tender (20-25 mins)',
          'Add sugar, cardamom pods, mix well',
        ],
      },
      {
        step: 3,
        title: 'Add Nuts',
        details: [
          'Add almonds and raisins, mix well',
          'Cook until halwa thickens (5-10 mins)',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: ['Serve warm, garnished with additional nuts'],
      },
    ],
    allergies: ['dairy', 'nuts'],
    cookingTime: '1 hr',
    difficulty: 'Easy',
  },

  // Tandoori Roti Recipe
  {
    id: 17,
    name: 'Tandoori Roti',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1GTmP0ZRRdE98i5pWCHoehKJTmZnzsPXT/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'wheat', quantity: '2 cups (250g) flour'},
      {name: 'salt', quantity: '1 tsp'},
      {name: 'water', quantity: '1/2 cup (120ml)'},
      {name: 'ghee', quantity: '1 tbsp (15ml)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Dough',
        details: [
          'In bowl, combine:',
          '- Wheat flour',
          '- Salt (1 tsp)',
          '- Water (as needed)',
          'Knead into smooth dough',
          'Set aside for 10 mins',
        ],
      },
      {
        step: 2,
        title: 'Shape Roti',
        details: [
          'Divide dough into equal portions',
          'Roll each portion into a flat disc',
        ],
      },
      {
        step: 3,
        title: 'Cook Roti',
        details: [
          'Heat tandoor or oven to high heat',
          'Cook roti until golden brown on both sides (2-3 mins each side)',
          'Brush with ghee',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: ['Serve hot with curry or kebabs'],
      },
    ],
    allergies: ['gluten', 'dairy'],
    cookingTime: '30 mins',
    difficulty: 'Easy',
  },

  // Chicken Jalfrezi Recipe
  {
    id: 18,
    name: 'Chicken Jalfrezi',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1ZtnhjwJMG9UDoISLC_E8UoMvtSM-U4er/view?usp=sharing',
    servings: 4,
    ingredients: [
      {name: 'chicken', quantity: '500g, boneless pieces'},
      {name: 'bellpeppers', quantity: '2 medium, sliced'},
      {name: 'onions', quantity: '2 medium, sliced'},
      {name: 'tomatoes', quantity: '2 medium, chopped'},
      {name: 'ginger-garlic', quantity: '1 tbsp (15g)'},
      {name: 'greenchili', quantity: '2, sliced'},
      {name: 'redchili', quantity: '1 tsp powder'},
      {name: 'coriander', quantity: '1 tsp powder'},
      {name: 'cumin', quantity: '1 tsp'},
      {name: 'oil', quantity: '1/4 cup (60ml)'},
      {name: 'garammasala', quantity: '1 tsp'},
      {name: 'cilantro', quantity: '1/4 cup chopped (garnish)'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Chicken',
        details: [
          'Heat oil in large pan',
          'Add chicken pieces, cook until browned (5-7 mins)',
          'Remove chicken from pan, set aside',
        ],
      },
      {
        step: 2,
        title: 'Cook Jalfrezi',
        details: [
          'In same pan, add cumin seeds',
          'Fry until fragrant (1 min)',
          'Add sliced onions and bell peppers, cook until softened (5 mins)',
          'Add ginger-garlic, cook for 1 min',
          'Add chopped tomatoes, cook until softened (3 mins)',
          'Add red chili powder, coriander powder',
          'Cook for 2 mins',
          'Return chicken to pan, mix well',
        ],
      },
      {
        step: 3,
        title: 'Simmer',
        details: [
          'Add 1/2 cup water, bring to boil',
          'Reduce heat, cover, and simmer for 15-20 mins',
          'Stir occasionally until chicken is tender',
          'Sprinkle garam masala, mix well',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: [
          'Garnish with:',
          '- Cilantro',
          '- Green chili',
          '- Lemon wedges',
          'Serve with naan or rice',
        ],
      },
    ],
    allergies: [],
    cookingTime: '1 hr',
    difficulty: 'Easy',
  },

  // Pakora Recipe
  {
    id: 19,
    name: 'Pakora',
    cuisine: 'Pakistani',
    image:
      'https://drive.google.com/file/d/1ZtnhjwJMG9UDoISLC_E8UoMvtSM-U4er/view?usp=sharing ',
    servings: 6,
    ingredients: [
      {name: 'chickpea', quantity: '1 cup (120g) flour'},
      {name: 'onions', quantity: '1 medium, thinly sliced'},
      {name: 'potatoes', quantity: '1 medium, thinly sliced'},
      {name: 'spinach', quantity: '1 cup, chopped'},
      {name: 'greenchili', quantity: '2, finely chopped'},
      {name: 'coriander', quantity: '1/4 cup chopped'},
      {name: 'cumin', quantity: '1 tsp powder'},
      {name: 'redchili', quantity: '1/2 tsp powder'},
      {name: 'water', quantity: '1/2 cup (120ml)'},
      {name: 'oil', quantity: '1 cup (240ml), for frying'},
    ],
    recipeSteps: [
      {
        step: 1,
        title: 'Prepare Batter',
        details: [
          'In bowl, combine:',
          '- Chickpea flour',
          '- Cumin powder',
          '- Red chili powder',
          '- Salt (1/2 tsp)',
          'Add water, mix until smooth batter forms',
        ],
      },
      {
        step: 2,
        title: 'Add Vegetables',
        details: [
          'Add sliced onions, potatoes, spinach, green chili, and chopped coriander to batter',
          'Mix well until fully coated',
        ],
      },
      {
        step: 3,
        title: 'Fry Pakoras',
        details: [
          'Heat oil in deep pan over medium heat',
          'Drop spoonfuls of batter into hot oil',
          'Fry until golden brown (2-3 mins each side)',
          'Drain on paper towels',
        ],
      },
      {
        step: 4,
        title: 'Serving',
        details: ['Serve hot with mint chutney or ketchup'],
      },
    ],
    allergies: [],
    cookingTime: '30 mins',
    difficulty: 'Easy',
  },
];
